export const URL = "http://localhost:3001/";
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME'
export const FILTER_PRICE_BY_RANGE = 'FILTER_PRICE_BY_RANGE'
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE'
export const GET_INFO_GOOGLE = "GET_INFO_GOOGLE";
export const LOCAL_LOGIN = "LOCAL_LOGIN";
export const SIGNUP = "SIGNUP";
export const GET_USER = "GET_USER";
export const GET_CATEGORIES="GET_CATEGORIES";
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";