export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME'
export const FILTER_PRICE_BY_RANGE = 'FILTER_PRICE_BY_RANGE'
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE'